config/routes.rb
Rails.application.routes.draw do
  resources :pages
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  
  # Defines the root paths for authentication
  resource :registration
  resource :session
  resource :password_reset
  resource :password

  # Defines the root path route ("/")
  root "main#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
    attribute :user
end

app/models/page.rb
class Page < ApplicationRecord
end

app/models/password_reset.rb
class PasswordReset < ApplicationRecord
end

app/models/registration.rb
class Registration < ApplicationRecord
end

app/models/session.rb
class Session < ApplicationRecord
    
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password

    validates :email, presence: true
    normalizes :email, with: ->(email) {email.strip.downcase}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
    private
        def current_user
            Current.user ||= authenticate_user_from_session
        end
        helper_method :current_user

        def authenticate_user_from_session
            User.find_by(id: session[:user_id])
        end

        def user_signed_in
            current_user.present?
        end
        helper_method :user_signed_in

        def login(user)
           Current.user = user
           reset_session
           session[:user_id] = user.id
        end

        def logout(user)
            Current.user = nil
            reset_session
        end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
    def index
        
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :set_page, only: %i[ show edit update destroy ]

  # GET /pages or /pages.json
  def index
    @pages = Page.all
  end

  # GET /pages/1 or /pages/1.json
  def show
  end

  # GET /pages/new
  def new
    @page = Page.new
  end

  # GET /pages/1/edit
  def edit
  end

  # POST /pages or /pages.json
  def create
    @page = Page.new(page_params)

    respond_to do |format|
      if @page.save
        format.html { redirect_to page_url(@page), notice: "Page was successfully created." }
        format.json { render :show, status: :created, location: @page }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pages/1 or /pages/1.json
  def update
    respond_to do |format|
      if @page.update(page_params)
        format.html { redirect_to page_url(@page), notice: "Page was successfully updated." }
        format.json { render :show, status: :ok, location: @page }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pages/1 or /pages/1.json
  def destroy
    @page.destroy!

    respond_to do |format|
      format.html { redirect_to pages_url, notice: "Page was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_page
      @page = Page.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def page_params
      params.require(:page).permit(:name, :content, :ancestry)
    end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
    def new
        @user = User.new
    end

    def create
        @user = User.new(registration_params)
        if @user.save
            login @user
            redirect_to root_path 
        else
            render :new
        end
    end

    private
        def registration_params
            params.require(:user).permit(:email, :password, :password_confirmation)
        end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new 
    end

    def create
        if user = User.authenticate_by(email: params[:email], password: params[:password])
            login user 
            redirect_to root_path, notice: "You have signed in successfully."
        else
            flash[:alert] = "Invalid email or password"
            render :new, status: :unprocessable_entity
        end
    end

    def destroy
        logout current_user
        redirect_to root_path, notice: "You have been logged out"
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MassiveContent</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div><%= notice %></div>
    <div><%= alert %></div>

    <% if user_signed_in %>
      <%= link_to "Edit Password", edit_password_path %>
      <%= button_to "Log out", session_path, method: :delete %>
    <% else %>
      <%= link_to "Sign Up", new_registration_path %>
      <%= link_to "Log In", new_session_path %>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/main/index.html.erb
<h1>Homepage</h1>

app/views/names/_form.html.erb
<%= form_with(model: name) do |form| %>
  <% if name.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(name.errors.count, "error") %> prohibited this name from being saved:</h2>

      <ul>
        <% name.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.text_area :content %>
  </div>

  <div>
    <%= form.label :ancestry, style: "display: block" %>
    <%= form.text_field :ancestry %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/pages/_form.html.erb
<%= form_with(model: page) do |form| %>
  <% if page.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
        <% page.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.text_area :content %>
  </div>

  <div>
    <%= form.label :ancestry, style: "display: block" %>
    <%= form.text_field :ancestry %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/pages/_page.html.erb
<div id="<%= dom_id page %>">
  <p>
    <strong>Name:</strong>
    <%= page.name %>
  </p>

  <p>
    <strong>Content:</strong>
    <%= page.content %>
  </p>

  <p>
    <strong>Ancestry:</strong>
    <%= page.ancestry %>
  </p>

</div>

app/views/pages/edit.html.erb
<h1>Editing page</h1>

<%= render "form", page: @page %>

<br>

<div>
  <%= link_to "Show this page", @page %> |
  <%= link_to "Back to pages", pages_path %>
</div>

app/views/pages/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Pages</h1>

<div id="pages">
  <% @pages.each do |page| %>
    <%= render page %>
    <p>
      <%= link_to "Show this page", page %>
    </p>
  <% end %>
</div>

<%= link_to "New page", new_page_path %>

app/views/pages/new.html.erb
<h1>New page</h1>

<%= render "form", page: @page %>

<br>

<div>
  <%= link_to "Back to pages", pages_path %>
</div>

app/views/pages/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @page %>

<div>
  <%= link_to "Edit this page", edit_page_path(@page) %> |
  <%= link_to "Back to pages", pages_path %>

  <%= button_to "Destroy this page", @page, method: :delete %>
</div>